policies:

   - name: s3-configure-standards-real-time
     resource: s3
     description: |
       This policy is triggered when a new S3 bucket is created and it applies
       the AWS AES256 Default Bucket Encryption, Tags the creators ID, enables
       object versioning, configures the bucket lifecycle and enables logging.
     mode:
       type: cloudtrail
       events:
         - CreateBucket
       role: arn:aws:iam::{account_id}:role/AWS_DEFAULT_LAMBDA_EXECUTION_ROLE
       timeout: 200
     actions:
       - type: auto-tag-user
         tag: CreatorName
       - type: set-bucket-encryption
       - type: toggle-versioning
         enabled: true
       - type: configure-lifecycle
         rules:
          - ID: company-s3-lifecycle
            Status: Enabled
            Filter:
               Prefix: /
            Transitions:
              - Days: 30
                StorageClass: INTELLIGENT_TIERING
            NoncurrentVersionExpiration:
                NoncurrentDays: 120